### POST PRODUCT
POST http://localhost:5000/products
Content-Type: application/json

{
  "name":"Anor",
  "price": 12000,
  "count": 50,
  "user_id":2
}


### GET PRODUCT
GET http://localhost:5000/products
Content-Type: application/json

### GET ONE PRODUCT
GET http://localhost:5000/products/aa5154f5-c9f0-4458-805c-baac72bb9a78
Content-Type: application/json


### DELETE PRODUCT
DELETE http://localhost:5000/products/ee7f5627-a0c8-4bf3-827c-4fa5a0ea7465
Content-Type: application/json


### UPDATE PRODUCT
PUT http://localhost:5000/products/749d7396-0fd8-48df-8b7d-4152eb30c1f5
Content-Type: application/json

{
  "name":"Behi",
  "price": 52000,
  "count": 120
}
