### POST PRODUCT
POST http://localhost:5000/products
Content-Type: application/json

{
  "name":"Anor",
  "price": 12000,
  "count": 50,
  "user_id":2
}


### GET PRODUCT
GET http://localhost:5000/products
Content-Type: application/json

### GET ONE PRODUCT
GET http://localhost:5000/products/aa5154f5-c9f0-4458-805c-baac72bb9a78
Content-Type: application/json


### DELETE PRODUCT
DELETE http://localhost:5000/products/ee7f5627-a0c8-4bf3-827c-4fa5a0ea7465
Content-Type: application/json